Allow hostname verification to be disabled through arquillian.xml
OpenLiberty/liberty-arquillian pull request #48
Opened 2019-04-02 13:32 UTC by codingchili

#### Short description of what this resolves:
Allows disabling hostname verification for the WLPRestClient used in the remote adapter.

#### Changes proposed in this pull request:
- adds 'disableHostnameVerification', boolean: true|false as a configuration option to arquillian.xml
- hostname verification is enabled by default.
- configures the SSLContext with a trust manager that trusts all certificates.
- sets the NoopHostnameVerifier on the http client.

**Fixes**: #47

2019-04-19 16:01 UTC, aguibert reviewed
hi, thanks for the PR!

Code changes look good, but lets change the property name from `disableHostnameVerification` to `hostnameVerificationEnabled` to avoid the double-negative.

2019-04-21 09:46 UTC, codingchili commented
Hi, thanks!

Updating next Tuesday.

2019-04-23 09:10 UTC, Azquelt requested changes
Disabling hostname verification is not the same as trusting all certificates.

If the intent is just to disable hostname verification, it needs to do just that (i.e. just the change to add the `NoopHostnameVerifier`).

If the intent is to allow untrusted certificates, then I think the name of the configuration parameter should be changed. Maybe something like `connectionSecurityEnabled` or `useInsecureConnection`?

2026-05-23 00:15 UTC, cherylking commented
@Azquelt Is this still needed/wanted? I am inclined to close this since it has sat here for 7 years untouched.

2026-05-23 10:21 UTC, Azquelt commented
I think we can assume the original author is no longer interested and it can be closed.

2026-05-23 12:55 UTC, closed without merging